package com.company;

public class ConversionAStrings {

    public static String entroAString(int enteroAConvertir){

        return switch (enteroAConvertir) {
            case -8 -> "menos ocho";
            case -7 -> "menos siete";
            case -6 -> "menos seis";
            case -5 -> "menos cinco";
            case -4 -> "menos cuatro";
            case -3 -> "menos tres";
            case -2 -> "menos dos";
            case -1 -> "menos uno";
            case 0 -> "cero";
            case 1 -> "uno";
            case 2 -> "dos";
            case 3 -> "tres";
            case 4 -> "cuatro";
            case 5 -> "cinco";
            case 6 -> "seis";
            case 7 -> "siete";
            case 8 -> "ocho";
            case 9 -> "nueve";
            case 10 -> "diez";
            case 11 -> "once";
            case 12 -> "doce";
            case 13 -> "trece";
            case 14 -> "catorce";
            case 15 -> "quince";
            case 16 -> "dieciseis";
            case 17 -> "diecisiete";
            case 18 -> "dieciocho";
            case 19 -> "diecinueve";
            case 20 -> "veinte";
            case 21 -> "veintiuno";
            case 22 -> "veintidos";
            case 23 -> "veintitres";
            case 24 -> "veinticuatro";
            case 25 -> "veinticinco";
            case 26 -> "veintiseis";
            case 27 -> "veintisiete";
            case 28 -> "veintiocho";
            case 29 -> "veintinueve";
            case 30 -> "treinta";
            case 31 -> "treinta y uno";
            case 32 -> "treinta y dos";
            case 33 -> "treinta y tres";
            case 34 -> "treinta y cuatro";
            case 35 -> "treinta y cinco";
            case 36 -> "treinta y seis";
            case 37 -> "treinta y siete";
            case 38 -> "treinta y ocho";
            case 39 -> "treinta y nueve";
            case 40 -> "cuarenta";
            case 41 -> "cuarenta y uno";
            case 42 -> "cuarenta y dos";
            case 43 -> "cuarenta y tres";
            case 44 -> "cuarenta y cuatro";
            case 45 -> "cuarenta y cinco";
            case 46 -> "cuarenta y seis";
            case 47 -> "cuarenta y siete";
            case 48 -> "cuarenta y ocho";
            case 49 -> "cuarenta y nueve";
            case 50 -> "cincuenta";
            case 51 -> "cincuenta y uno";
            case 52 -> "cincuenta y dos";
            case 53 -> "cincuenta y tres";
            case 54 -> "cincuenta y cuatro";
            case 55 -> "cincuenta y cinco";
            case 56 -> "cincuenta y seis";
            case 57 -> "cincuenta y siete";
            case 58 -> "cincuenta y ocho";
            case 59 -> "cincuenta y nueve";
            case 60 -> "sesenta";
            case 61 -> "sesenta y uno";
            case 62 -> "sesenta y dos";
            case 63 -> "sesenta y tres";
            case 64 -> "sesenta y cuatro";
            case 65 -> "sesenta y cinco";
            case 66 -> "sesenta y seis";
            case 67 -> "sesenta y siete";
            case 68 -> "sesenta y ocho";
            case 69 -> "sesenta y nueve";
            case 70 -> "setenta";
            case 71 -> "setenta y uno";
            case 72 -> "setenta y dos";
            case 73 -> "setenta y tres";
            case 74 -> "setenta y cuatro";
            case 75 -> "setenta y cinco";
            case 76 -> "setenta y seis";
            case 77 -> "setenta y siete";
            case 78 -> "setenta y ocho";
            case 79 -> "setenta y nueve";
            case 80 -> "ochenta";
            case 81 -> "ochenta y uno";
            default -> null;
        };
    }
}
